# Generated by Django 2.0.3 on 2018-03-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamname',
            field=models.CharField(default='Name', max_length=20),
            preserve_default=False,
        ),
    ]
